# Generated by Django 4.2 on 2023-05-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='repassword',
        ),
    ]
